version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    expose:
      - '5432'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=defaultdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6LPV4p&O#aV9
    volumes:
      - my-db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  my-db: