# Generated by Django 5.1.5 on 2025-01-17 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('custom_sprite', models.ImageField(blank=True, null=True, upload_to='trainers/sprites/')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerBox',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('box_number', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='trainer_data.trainer')),
            ],
            options={
                'verbose_name_plural': 'Trainer Boxes',
            },
        ),
        migrations.CreateModel(
            name='TrainerPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mote', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('cur_hp', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_hp', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('attack', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('defense', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('speed', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_attack', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_defense', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon_api.pokemonability')),
                ('held_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon_api.item')),
                ('moves', models.ManyToManyField(blank=True, to='pokemon_api.move')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon_api.pokemonnature')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainereds', to='pokemon_api.pokemon')),
                ('types', models.ManyToManyField(blank=True, to='pokemon_api.type')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerBoxSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='trainer_data.trainerbox')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trainer_data.trainerpokemon')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('trainer_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_teams', to='trainer_data.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='trainer_data.trainerteam'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainer', to='trainer_data.trainerteam'),
        ),
    ]
