# Generated by Django 5.1.5 on 2025-01-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='form',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
