# Generated by Django 5.1.5 on 2025-01-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0002_trainerpokemon_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
