# Generated by Django 5.1.5 on 2025-01-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0005_remove_trainer_streamer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='trainer_data.trainerteam'),
        ),
    ]
