# Generated by Django 5.1.5 on 2025-01-25 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0006_alter_trainer_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='ev_attack',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='ev_defense',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='ev_hp',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='ev_special_attack',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='ev_special_defense',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='ev_speed',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='iv_attack',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='iv_defense',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='iv_hp',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='iv_special_attack',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='iv_special_defense',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='iv_speed',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
