# Generated by Django 5.1.5 on 2025-01-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0004_item_flavor_text_localizations_and_more'),
        ('trainer_data', '0007_trainerpokemon_ev_attack_trainerpokemon_ev_defense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='mega_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megas', to='pokemon_api.pokemonability'),
        ),
        migrations.AlterField(
            model_name='trainerpokemon',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemons', to='pokemon_api.pokemonability'),
        ),
    ]
