# Generated by Django 5.1.5 on 2025-02-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0008_trainerpokemon_mega_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
