# Generated by Django 5.1.5 on 2025-03-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0009_trainerpokemon_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerpokemon',
            name='notes',
        ),
    ]
