# Generated by Django 5.1.5 on 2025-03-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0024_remove_streamer_trainer'),
        ('trainer_data', '0010_remove_trainerpokemon_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='event_api.streamer'),
        ),
    ]
