# Generated by Django 5.1.5 on 2025-03-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0011_trainer_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainer',
            new_name='streamer',
        ),
    ]
