# Generated by Django 5.1.5 on 2025-05-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0012_rename_trainer_trainer_streamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='custom_sprite',
        ),
    ]
