# Generated by Django 5.1.5 on 2025-05-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0014_alter_trainer_options_trainer_gym_badge_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
