# Generated by Django 5.1.5 on 2025-06-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0015_alter_trainer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='streamer',
        ),
    ]
