# Generated by Django 5.1.5 on 2025-07-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0016_remove_trainer_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
