# Generated by Django 5.1.5 on 2025-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0017_trainerpokemon_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='exp',
            field=models.IntegerField(null=True),
        ),
    ]
