# Generated by Django 5.1.5 on 2025-07-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0018_trainerpokemon_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpokemon',
            name='pid',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
