# Generated by Django 5.1.5 on 2025-07-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0019_alter_trainerpokemon_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='is_shiny',
            field=models.BooleanField(default=False),
        ),
    ]
