# Generated by Django 5.1.5 on 2025-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0020_trainerpokemon_is_shiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='enc_data',
            field=models.BinaryField(null=True),
        ),
    ]
