# Generated by Django 5.1.5 on 2025-08-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0021_trainerpokemon_enc_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpokemon',
            name='enc_data',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
