# Generated by Django 5.1.5 on 2025-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0022_alter_trainerpokemon_enc_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
