# Generated by Django 5.1.5 on 2025-08-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0023_trainer_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mons', to='trainer_data.trainer'),
        ),
    ]
