# Generated by Django 5.1.5 on 2025-08-27 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0024_trainerpokemon_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpokemon',
            name='force_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerpokemon',
            name='marked_for_market_until',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
