# Generated by Django 5.1.5 on 2026-03-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_data', '0025_trainerpokemon_force_disabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBattleBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_box', to='trainer_data.trainer')),
            ],
            options={
                'verbose_name_plural': 'Trainer Boxes',
            },
        ),
        migrations.CreateModel(
            name='TrainerBattleBoxSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='trainer_data.trainerbattlebox')),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer_data.trainerpokemon')),
            ],
        ),
    ]
