# Generated by Django 5.1.5 on 2025-07-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_api', '0059_remove_gameevent_game_mod_gamemod_event_and_more'),
        ('rewards_api', '0012_alter_reward_pokemon_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryGiftQuerySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('run_times', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventory_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards_api.rewardbundle')),
                ('targets', models.ManyToManyField(to='event_api.mastersprofile')),
            ],
        ),
    ]
