# Generated by Django 5.1.5 on 2025-07-28 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('event_api', '0060_remove_streamerwildcardinventoryitem_streamer'),
        ('pokemon_api', '0008_item_item_bag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorygiftquerysequence',
            options={'verbose_name': 'Gift Log', 'verbose_name_plural': 'Gift Logs'},
        ),
        migrations.CreateModel(
            name='DirectGiftQuerySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('run_times', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('targets', models.ManyToManyField(to='event_api.mastersprofile')),
            ],
            options={
                'verbose_name': 'Direct Gift Log',
                'verbose_name_plural': 'Direct Gift Logs',
            },
        ),
        migrations.CreateModel(
            name='DirectGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Wildcard'), (2, 'Money')], default=2)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_api.item')),
                ('wildcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.wildcard')),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='admin_panel.directgiftquerysequence')),
            ],
        ),
    ]
