# Generated by Django 5.1.5 on 2025-07-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_inventorygiftquerysequence_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directgift',
            name='item',
        ),
    ]
