# Generated by Django 5.1.5 on 2025-07-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_directgift_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directgift',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Wildcard'), (0, 'Money')], default=0),
        ),
    ]
