# Generated by Django 5.1.5 on 2025-07-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_directgift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directgift',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
