# Generated by Django 5.1.5 on 2025-07-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_directgift_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directgiftquerysequence',
            options={'verbose_name': 'Correccion Directa', 'verbose_name_plural': 'Correcciones Directas'},
        ),
        migrations.AlterModelOptions(
            name='inventorygiftquerysequence',
            options={'verbose_name': 'Envío de Preset al Buzón', 'verbose_name_plural': 'Envío de Presets al Buzón'},
        ),
    ]
