# Generated by Django 5.1.5 on 2025-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_directgiftquerysequence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowdownToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
