# Generated by Django 5.1.5 on 2025-08-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_showdowntoken'),
        ('event_api', '0087_evolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanPokemonSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('run_on_save', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.mastersprofile')),
            ],
        ),
    ]
