# Generated by Django 5.1.5 on 2025-08-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_banpokemonsequence'),
        ('event_api', '0092_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='directgiftquerysequence',
            name='give_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directgiftquerysequence',
            name='targets',
            field=models.ManyToManyField(blank=True, null=True, to='event_api.mastersprofile'),
        ),
    ]
