# Generated by Django 5.1.5 on 2025-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_directgiftquerysequence_give_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorygiftquerysequence',
            name='give_all',
            field=models.BooleanField(default=False),
        ),
    ]
