# Generated by Django 5.1.5 on 2025-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_inventorygiftquerysequence_give_all'),
        ('event_api', '0092_sanction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygiftquerysequence',
            name='targets',
            field=models.ManyToManyField(blank=True, null=True, to='event_api.mastersprofile'),
        ),
    ]
