# Generated by Django 5.1.5 on 2025-08-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_inventorygiftquerysequencelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectGiftQuerySequenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=200)),
                ('performer', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.inventorygiftquerysequence')),
            ],
        ),
    ]
