# Generated by Django 5.1.5 on 2025-08-26 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_directgiftquerysequencelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directgiftquerysequencelog',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.directgiftquerysequence'),
        ),
    ]
