# Generated by Django 5.1.5 on 2025-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_directgiftquerysequencelog_sequence'),
        ('event_api', '0101_alter_newsletter_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directgiftquerysequence',
            name='targets',
            field=models.ManyToManyField(blank=True, to='event_api.mastersprofile'),
        ),
        migrations.AlterField(
            model_name='inventorygiftquerysequence',
            name='targets',
            field=models.ManyToManyField(blank=True, to='event_api.mastersprofile'),
        ),
    ]
