# Generated by Django 5.1.5 on 2025-08-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_directgiftquerysequence_targets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorygiftquerysequence',
            name='give_only_noobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorygiftquerysequence',
            name='give_only_pros',
            field=models.BooleanField(default=False),
        ),
    ]
