# Generated by Django 5.1.5 on 2025-08-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_inventorygiftquerysequence_give_only_noobs_and_more'),
        ('event_api', '0115_alter_newsletter_target_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorygiftquerysequence',
            name='give_all',
        ),
        migrations.RemoveField(
            model_name='inventorygiftquerysequence',
            name='give_only_noobs',
        ),
        migrations.RemoveField(
            model_name='inventorygiftquerysequence',
            name='give_only_pros',
        ),
        migrations.AddField(
            model_name='inventorygiftquerysequence',
            name='run_on_save',
            field=models.BooleanField(default=False, verbose_name='Ejecutar al guardar'),
        ),
        migrations.AddField(
            model_name='inventorygiftquerysequence',
            name='target_method',
            field=models.SmallIntegerField(choices=[(0, 'Todos'), (1, 'Pros'), (2, 'Noobs'), (3, 'Seleccionado')], default=0, verbose_name='Objetivos de envío'),
        ),
        migrations.AlterField(
            model_name='inventorygiftquerysequence',
            name='targets',
            field=models.ManyToManyField(blank=True, to='event_api.mastersprofile', verbose_name='Objetivos Seleccionados'),
        ),
    ]
