# Generated by Django 5.1.5 on 2025-08-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_remove_inventorygiftquerysequence_give_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygiftquerysequence',
            name='target_method',
            field=models.SmallIntegerField(choices=[(0, 'Todos'), (1, 'Pros'), (2, 'Noobs'), (3, 'Seleccionado')], default=3, verbose_name='Objetivos de envío'),
        ),
    ]
