# Generated by Django 5.1.5 on 2025-09-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_extractpokemondatasequence_extractionpokemonprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractpokemondatasequence',
            options={'verbose_name': 'Secuencia de extracción de datos Pokémon', 'verbose_name_plural': 'Secuencias de extracción Pokémon'},
        ),
    ]
