# Generated by Django 5.1.5 on 2025-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_alter_extractpokemondatasequence_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractpokemondatasequence',
            name='last_ran_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima ejecucion'),
        ),
    ]
