# Generated by Django 5.1.5 on 2025-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_alter_extractpokemondatasequence_last_ran_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionpokemonprocess',
            name='pokemon_mote',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Mote Pokemon'),
        ),
    ]
