# Generated by Django 5.1.5 on 2025-09-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_extractionpokemonprocess_pokemon_mote'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionpokemonprocess',
            name='search_starter',
            field=models.BooleanField(default=False, verbose_name='Buscar Elegido'),
        ),
    ]
