# Generated by Django 5.1.5 on 2025-09-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_extractionpokemonprocess_search_starter'),
        ('pokemon_api', '0010_alter_pokemonnature_stat_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionpokemonprocess',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_targeted', to='pokemon_api.pokemon', verbose_name='Pokemon Objetivo'),
        ),
    ]
