# Generated by Django 5.1.5 on 2025-08-28 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_api', '0097_wildcardupdatelog'),
        ('trainer_data', '0025_trainerpokemon_force_disabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BankPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=50)),
                ('enc_data', models.FileField(null=True, upload_to='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_api.mastersprofile')),
                ('trainer_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer_data.trainerpokemon')),
            ],
        ),
    ]
