# Generated by Django 5.1.5 on 2025-08-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_market', '0002_marketblocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketblocklog',
            name='blocked_until',
            field=models.DateTimeField(),
        ),
    ]
