# Generated by Django 5.1.5 on 2025-08-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0097_wildcardupdatelog'),
        ('new_market', '0003_alter_marketblocklog_blocked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCooldownLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.IntegerField(null=True)),
                ('blocked_until', models.DateTimeField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.mastersprofile')),
            ],
        ),
    ]
