# Generated by Django 5.1.5 on 2025-08-28 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0097_wildcardupdatelog'),
        ('new_market', '0004_marketcooldownlog'),
        ('pokemon_api', '0010_alter_pokemonnature_stat_down_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon_api.item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_api.mastersprofile')),
            ],
        ),
    ]
