# Generated by Django 5.1.5 on 2025-08-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0098_segmentconfiguration'),
        ('new_market', '0005_bankitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketBank',
        ),
        migrations.AlterField(
            model_name='bankitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banked_items', to='event_api.mastersprofile'),
        ),
        migrations.AlterField(
            model_name='bankpokemon',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banked_pokemons', to='event_api.mastersprofile'),
        ),
    ]
