# Generated by Django 5.1.5 on 2025-08-31 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0111_remove_newsletter_for_noobs_and_more'),
        ('new_market', '0006_delete_marketbank_alter_bankitem_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_owned', to='event_api.mastersprofile')),
                ('second_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_joined', to='event_api.mastersprofile')),
            ],
        ),
    ]
