# Generated by Django 5.1.5 on 2025-08-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_market', '0007_marketroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
