# Generated by Django 5.1.5 on 2025-09-01 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0116_masterssegmentsettings_death_count_display'),
        ('new_market', '0008_marketroom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketroom',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BankWildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banked_wildcards', to='event_api.mastersprofile')),
                ('wildcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event_api.wildcard')),
            ],
        ),
        migrations.CreateModel(
            name='MarketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='new_market.bankitem')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='new_market.bankpokemon')),
                ('wildcards', models.ManyToManyField(to='new_market.bankwildcard')),
            ],
        ),
    ]
