# Generated by Django 5.1.5 on 2025-06-01 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('event_api', '0041_mastersprofile_coached'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(blank=True, max_length=50, null=True)),
                ('trade_locked', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'pokemon_api'), ('model', 'item')), models.Q(('app_label', 'trainer_data'), ('model', 'trainerpokemon')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.streamer')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Borrador'), (1, 'Abierto'), (2, 'Cerrado'), (3, 'Cancelado')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.streamer')),
            ],
        ),
    ]
