# Generated by Django 5.1.5 on 2025-06-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.SmallIntegerField(choices=[(0, 'Money'), (1, 'Item'), (3, 'Pokemon')], default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('banked_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketed', to='market.bankedasset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='market.marketpost')),
            ],
        ),
    ]
