# Generated by Django 5.1.5 on 2025-06-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='pero que ha pasado acho', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='marketpost',
            name='already_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='banked_asset',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('quantity__gt', 0)), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketed', to='market.bankedasset'),
        ),
    ]
