# Generated by Django 5.1.5 on 2025-06-01 07:48

import django.db.models.deletion
import market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0041_mastersprofile_coached'),
        ('market', '0003_marketalert_marketpost_already_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketslot',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='market.marketpost'),
        ),
        migrations.CreateModel(
            name='MarketPostOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Borrador'), (1, 'Abierto'), (2, 'Cerrado'), (3, 'Cancelado')], default=0)),
                ('already_closed', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.streamer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='market.marketpost')),
            ],
            bases=(models.Model, market.models.MarketTransactor),
        ),
        migrations.AddField(
            model_name='marketpost',
            name='selected_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.marketpostoffer'),
        ),
        migrations.AddField(
            model_name='marketslot',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='market.marketpostoffer'),
        ),
    ]
