# Generated by Django 5.1.5 on 2025-06-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_marketslot_post_marketpostoffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.marketpost')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.marketpostoffer')),
            ],
        ),
    ]
