# Generated by Django 5.1.5 on 2025-08-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0076_newsletter_for_staff'),
        ('market', '0006_alter_bankedasset_user_alter_marketpost_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankedasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banked_assets', to='event_api.mastersprofile'),
        ),
    ]
