# Generated by Django 5.1.5 on 2025-08-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_marketpost_created_at_alter_bankedasset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketslot',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.marketpostoffer'),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.marketpost'),
        ),
    ]
