# Generated by Django 5.1.5 on 2025-01-18 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
        ('trainer_data', '0002_trainerpokemon_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('TYPE', models.SmallIntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso')])),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trainer_data.trainer')),
            ],
        ),
    ]
