# Generated by Django 5.1.5 on 2025-01-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_cointransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cointransaction',
            options={'verbose_name': 'Economy Log', 'verbose_name_plural': 'Economy Logs'},
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
    ]
