# Generated by Django 5.1.5 on 2025-01-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0003_alter_cointransaction_options_cointransaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='TYPE',
            field=models.SmallIntegerField(choices=[(0, 'Ingreso'), (1, 'Egreso')], default=0),
        ),
    ]
