# Generated by Django 5.1.5 on 2025-01-20 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0004_alter_cointransaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sprite', models.ImageField(upload_to='wildcards/')),
                ('description', models.TextField(default='')),
                ('quality', models.SmallIntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Rare'), (3, 'Legendary')], default=0)),
            ],
        ),
    ]
