# Generated by Django 5.1.5 on 2025-01-20 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0005_wildcard'),
        ('trainer_data', '0002_trainerpokemon_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streamer', to='trainer_data.trainer')),
                ('wildcards', models.ManyToManyField(blank=True, to='event_api.wildcard')),
            ],
        ),
        migrations.CreateModel(
            name='StreamPlatformUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.streamer')),
            ],
        ),
    ]
