# Generated by Django 5.1.5 on 2025-01-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0006_wildcard_is_active_streamer_streamplatformurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='wildcards',
        ),
    ]
