# Generated by Django 5.1.5 on 2025-01-20 01:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0007_remove_streamer_wildcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerWildcardInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcard_inventory', to='event_api.streamer')),
                ('wildcard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_api.wildcard')),
            ],
        ),
    ]
