# Generated by Django 5.1.5 on 2025-01-20 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0008_streamerwildcardinventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcard',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
