# Generated by Django 5.1.5 on 2025-01-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0009_alter_wildcard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='extra_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
