# Generated by Django 5.1.5 on 2025-01-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0010_wildcard_extra_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcard',
            name='sprite',
            field=models.ImageField(blank=True, null=True, upload_to='wildcards/'),
        ),
    ]
