# Generated by Django 5.1.5 on 2025-01-20 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0012_coachprofile_trainerprofile'),
        ('trainer_data', '0002_trainerpokemon_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='coached_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='trainer_data.trainer'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='trainer_data.trainer'),
        ),
    ]
