# Generated by Django 5.1.5 on 2025-01-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0013_alter_coachprofile_coached_trainer_and_more'),
        ('trainer_data', '0002_trainerpokemon_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='coached_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='trainer_data.trainer'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='trainer_data.trainer'),
        ),
    ]
