# Generated by Django 5.1.5 on 2025-01-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0014_alter_coachprofile_coached_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
