# Generated by Django 5.1.5 on 2025-01-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0015_loaderthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='special_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
