# Generated by Django 5.1.5 on 2025-01-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0016_wildcard_special_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='always_available',
            field=models.BooleanField(default=False),
        ),
    ]
