# Generated by Django 5.1.5 on 2025-01-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0017_wildcard_always_available'),
        ('trainer_data', '0006_alter_trainer_current_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildcardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default='No details provided')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_logs', to='trainer_data.trainer')),
                ('wildcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_logs', to='event_api.wildcard')),
            ],
        ),
    ]
