# Generated by Django 5.1.5 on 2025-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0019_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='savefile',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
    ]
