# Generated by Django 5.1.5 on 2025-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0020_savefile_accessible'),
        ('rewards_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='rewards',
            field=models.ManyToManyField(to='rewards_api.rewardbundle'),
        ),
    ]
