# Generated by Django 5.1.5 on 2025-03-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0021_streamer_rewards'),
        ('trainer_data', '0010_remove_trainerpokemon_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='streamer', to='trainer_data.trainer'),
        ),
    ]
