# Generated by Django 5.1.5 on 2025-03-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0023_alter_streamer_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='trainer',
        ),
    ]
