# Generated by Django 5.1.5 on 2025-04-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0025_remove_streamer_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_file', models.FileField(upload_to='mods/')),
                ('mod_name', models.CharField(max_length=50)),
                ('mod_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date_from', models.DateTimeField()),
                ('available_date_to', models.DateTimeField()),
                ('force_available', models.BooleanField()),
                ('game_mod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='event_api.gamemod')),
            ],
        ),
        migrations.CreateModel(
            name='StreamerGameMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_file', models.FileField(upload_to='mods/streamer/')),
                ('game_mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='event_api.gamemod')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='event_api.streamer')),
            ],
        ),
    ]
