# Generated by Django 5.1.5 on 2025-05-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0026_gamemod_gameevent_streamergamemod'),
        ('trainer_data', '0012_rename_trainer_trainer_streamer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='streamer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MastersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.SmallIntegerField(choices=[(0, 'Trainer'), (1, 'Coach'), (2, 'Admin')], default=0)),
                ('trainer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='trainer_data.trainer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masters_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CoachProfile',
        ),
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
    ]
