# Generated by Django 5.1.5 on 2025-05-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0027_remove_trainerprofile_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='handler_key',
            field=models.CharField(blank=True, help_text="Identificador del handler a usar (ej: 'give_item')", max_length=100, null=True),
        ),
    ]
