# Generated by Django 5.1.5 on 2025-05-12 03:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0028_wildcard_handler_key'),
        ('pokemon_api', '0004_item_flavor_text_localizations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveItemHandlerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_item_wildcard', to='pokemon_api.item')),
                ('wildcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='give_item_settings', to='event_api.wildcard')),
            ],
        ),
    ]
