# Generated by Django 5.1.5 on 2025-05-12 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0029_giveitemhandlersettings'),
        ('pokemon_api', '0004_item_flavor_text_localizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveitemhandlersettings',
            name='item_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_item_wildcard', to='pokemon_api.item'),
        ),
        migrations.AlterField(
            model_name='giveitemhandlersettings',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='giveitemhandlersettings',
            name='wildcard',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_item_settings', to='event_api.wildcard'),
        ),
        migrations.CreateModel(
            name='GiveMoneyHandlerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('wildcard', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_money_settings', to='event_api.wildcard')),
            ],
        ),
    ]
