# Generated by Django 5.1.5 on 2025-05-12 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0030_alter_giveitemhandlersettings_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='death_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
