# Generated by Django 5.1.5 on 2025-05-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0031_mastersprofile_death_count'),
        ('trainer_data', '0012_rename_trainer_trainer_streamer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('delimiter_key', models.CharField(blank=True, help_text="Identificador del handler a usar (ej: 'second_badge')", max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='giveitemhandlersettings',
            name='item_bag',
            field=models.CharField(blank=True, choices=[('berries', 'berries bag'), ('meds', 'meds bag'), ('tms', 'tms bag'), ('keys', 'keys bag'), ('items', 'items bag')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeathLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('died_in', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=100)),
                ('mote', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_log', to='trainer_data.trainer')),
            ],
        ),
    ]
