# Generated by Django 5.1.5 on 2025-05-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0032_masterssegment_giveitemhandlersettings_item_bag_and_more'),
        ('trainer_data', '0012_rename_trainer_trainer_streamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='trainer_data.trainer'),
        ),
    ]
