# Generated by Django 5.1.5 on 2025-05-16 04:22

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CoinTransaction = apps.get_model("event_api", "CoinTransaction")
    MastersProfile = apps.get_model("event_api", "MastersProfile")
    transactions = CoinTransaction.objects.all()
    for transaction in transactions:
        profile = MastersProfile.objects.get(trainer=transaction.trainer, profile_type=0)
        transaction.profile = profile
        transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event_api', '0033_alter_mastersprofile_trainer'),
        ('trainer_data', '0012_rename_trainer_trainer_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions',
                                    to='event_api.mastersprofile'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transactions', to='trainer_data.trainer'),
        ),
        migrations.RunPython(forwards_func)
    ]
