# Generated by Django 5.1.5 on 2025-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0034_cointransaction_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='custom_sprite',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/sprites/'),
        ),
    ]
