# Generated by Django 5.1.5 on 2025-05-19 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0035_mastersprofile_custom_sprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='rom_name',
            field=models.CharField(default='Pokémon X', max_length=50),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='save_path',
            field=models.CharField(blank=True, default='%APPDATA%\\Lime3DS\\sdmc\\Nintendo 3DS\\00000000000000000000000000000000\\00000000000000000000000000000000\\title\\00040000\\00055d00\\data\\00000001', max_length=260, null=True),
        ),
        migrations.CreateModel(
            name='MastersSegmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True, verbose_name='Tramo Actual')),
                ('segment', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('available_community_skip', models.BooleanField(default=True, verbose_name='Skip de Comunidad Disponible')),
                ('community_pokemon_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(808)], verbose_name='Pokemon de comunidad')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments_settings', to='event_api.mastersprofile')),
            ],
            options={
                'verbose_name': 'Configuración de Tramo',
                'verbose_name_plural': 'Configuraciones de Tramo',
            },
        ),
    ]
