# Generated by Django 5.1.5 on 2025-05-19 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0036_mastersprofile_rom_name_mastersprofile_save_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveGameMoneyHandlerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('wildcard', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_game_money_settings', to='event_api.wildcard')),
            ],
        ),
    ]
