# Generated by Django 5.1.5 on 2025-05-19 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0037_givegamemoneyhandlersettings'),
        ('trainer_data', '0013_remove_trainer_custom_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcardlog',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_logs', to='trainer_data.trainer'),
        ),
    ]
