# Generated by Django 5.1.5 on 2025-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0039_deathlog_profile_alter_mastersprofile_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildcard',
            name='quality',
            field=models.SmallIntegerField(choices=[(0, 'Esteticos'), (1, 'Curacion'), (2, 'Protección'), (3, 'Boosteos'), (4, 'Items'), (5, 'Captura'), (6, 'Ataque'), (7, 'Economía'), (8, 'Retos'), (9, 'El Elegido')], default=0),
        ),
    ]
