# Generated by Django 5.1.5 on 2025-05-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0040_alter_wildcard_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='coached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='event_api.mastersprofile'),
        ),
    ]
