# Generated by Django 5.1.5 on 2025-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0041_mastersprofile_coached'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
