# Generated by Django 5.1.5 on 2025-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0042_cointransaction_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
