# Generated by Django 5.1.5 on 2025-06-30 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0043_mastersprofile_is_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imposter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='texto en MINUSCULAS para encontrar al impostor', max_length=100, unique=True)),
                ('coin_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImposterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('imposter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.imposter')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposters', to='event_api.mastersprofile')),
            ],
        ),
    ]
