# Generated by Django 5.1.5 on 2025-07-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0046_alter_mastersprofile_web_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePlatformUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=260)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_api.mastersprofile')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
    ]
