# Generated by Django 5.1.5 on 2025-07-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0047_profileplatformurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
