# Generated by Django 5.1.5 on 2025-07-07 06:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0048_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveRandomMoneyHandlerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('max_quantity', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('wildcard', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_random_money_settings', to='event_api.wildcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
