# Generated by Django 5.1.5 on 2025-07-07 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0049_giverandommoneyhandlersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerHandlerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('wildcard', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer_settings', to='event_api.wildcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
