# Generated by Django 5.1.5 on 2025-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0050_timerhandlersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
    ]
