# Generated by Django 5.1.5 on 2025-07-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0051_mastersprofile_is_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='event_api.mastersprofile'),
        ),
        migrations.AddField(
            model_name='wildcardlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcard_logs', to='event_api.mastersprofile'),
        ),
        migrations.AlterField(
            model_name='deathlog',
            name='pid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deathlog',
            name='species_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
