# Generated by Django 5.1.5 on 2025-07-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0054_masterssegmentsettings_attacks_received_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildcard',
            name='quality',
        ),
        migrations.AddField(
            model_name='wildcard',
            name='attack_level',
            field=models.SmallIntegerField(choices=[(0, 'Bajo/Especial'), (1, 'Medio'), (2, 'Fuerte')], default=0, help_text='Nivel de Ataque solo para comodines de ATAQUE', verbose_name='Nivel de Ataque'),
        ),
        migrations.AddField(
            model_name='wildcard',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Esteticos'), (1, 'Curacion'), (2, 'Protección'), (3, 'Boosteos'), (4, 'Items'), (5, 'Captura'), (6, 'Ataque'), (7, 'Economía'), (8, 'Retos'), (9, 'El Elegido')], default=0, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='masterssegmentsettings',
            name='tournament_league',
            field=models.CharField(choices=[('-', '------'), ('A', 'Liga A'), ('B', 'Liga B'), ('C', 'Liga C'), ('D', 'Liga D'), ('E', 'Liga E')], default='-', help_text='Liga a la que se llegó en este tramo', max_length=1, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='wildcard',
            name='sprite',
            field=models.ImageField(null=True, upload_to='wildcards/'),
        ),
    ]
