# Generated by Django 5.1.5 on 2025-07-24 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0055_remove_wildcard_quality_wildcard_attack_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamerwildcardinventoryitem',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildcard_inventory', to='event_api.streamer'),
        ),
    ]
