# Generated by Django 5.1.5 on 2025-07-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0056_alter_streamerwildcardinventoryitem_streamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathlog',
            name='pid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deathlog',
            name='species_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='deathlog',
            unique_together={('profile', 'species_name')},
        ),
    ]
