# Generated by Django 5.1.5 on 2025-07-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0057_alter_deathlog_pid_alter_deathlog_species_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='game_mod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='event_api.gamemod'),
        ),
    ]
