# Generated by Django 5.1.5 on 2025-07-27 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0058_alter_gameevent_game_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevent',
            name='game_mod',
        ),
        migrations.AddField(
            model_name='gamemod',
            name='event',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_mod', to='event_api.gameevent'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StreamerGameMod',
        ),
    ]
