# Generated by Django 5.1.5 on 2025-07-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0059_remove_gameevent_game_mod_gamemod_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamerwildcardinventoryitem',
            name='streamer',
        ),
    ]
