# Generated by Django 5.1.5 on 2025-07-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0060_remove_streamerwildcardinventoryitem_streamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='user',
        ),
    ]
