# Generated by Django 5.1.5 on 2025-07-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0061_remove_streamer_user'),
        ('market', '0006_alter_bankedasset_user_alter_marketpost_creator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streamer',
        ),
    ]
