# Generated by Django 5.1.5 on 2025-07-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0062_delete_streamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deathlog',
            name='died_in',
        ),
        migrations.RemoveField(
            model_name='deathlog',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='deathlog',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='wildcardlog',
            name='trainer',
        ),
        migrations.AddField(
            model_name='deathlog',
            name='dex_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deathlog',
            name='is_revive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='masterssegmentsettings',
            name='community_skip_used_in',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skip de Comunidad en'),
        ),
    ]
