# Generated by Django 5.1.5 on 2025-07-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0063_remove_deathlog_died_in_remove_deathlog_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deathlog',
            old_name='is_revive',
            new_name='revived',
        ),
    ]
