# Generated by Django 5.1.5 on 2025-07-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0064_rename_is_revive_deathlog_revived'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deathlog',
            unique_together=set(),
        ),
    ]
