# Generated by Django 5.1.5 on 2025-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0065_alter_deathlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='already_won_lysson',
            field=models.BooleanField(default=False),
        ),
    ]
