# Generated by Django 5.1.5 on 2025-07-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0066_mastersprofile_already_won_lysson'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.IntegerField()),
                ('species_name', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_mons', to='event_api.mastersprofile')),
            ],
        ),
    ]
