# Generated by Django 5.1.5 on 2025-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0067_bannedpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='starter_dex_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
