# Generated by Django 5.1.5 on 2025-07-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0068_mastersprofile_starter_dex_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedpokemon',
            options={'verbose_name': 'Pokemon Baneado', 'verbose_name_plural': 'Pokemon Baneados'},
        ),
        migrations.AlterModelOptions(
            name='cointransaction',
            options={'verbose_name': 'Transaccion', 'verbose_name_plural': 'Registro de Economia'},
        ),
        migrations.AlterModelOptions(
            name='deathlog',
            options={'verbose_name': 'Acta de Defunción', 'verbose_name_plural': 'Registro de muertes'},
        ),
        migrations.AlterModelOptions(
            name='gameevent',
            options={'verbose_name': 'Evento del Juego', 'verbose_name_plural': 'Eventos del Juego'},
        ),
        migrations.AlterModelOptions(
            name='gamemod',
            options={'verbose_name': 'Mod', 'verbose_name_plural': 'Mods'},
        ),
        migrations.AlterModelOptions(
            name='imposter',
            options={'verbose_name': 'Impostor', 'verbose_name_plural': 'Impostores'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Tablon de Noticias'},
        ),
        migrations.AlterModelOptions(
            name='wildcard',
            options={'verbose_name': 'Comodín', 'verbose_name_plural': 'Comodines'},
        ),
        migrations.AlterModelOptions(
            name='wildcardlog',
            options={'verbose_name': 'Registro de comodin', 'verbose_name_plural': 'Registro de comodines'},
        ),
    ]
