# Generated by Django 5.1.5 on 2025-07-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0069_alter_bannedpokemon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='in_pokemon_league',
            field=models.BooleanField(default=False),
        ),
    ]
