# Generated by Django 5.1.5 on 2025-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0070_mastersprofile_in_pokemon_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='free_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='requirements',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('Combate', 'Combate'), ('Especial', 'Especial'), ('Captura', 'Captura')], default='Combate', max_length=100),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='type',
            field=models.CharField(blank=True, choices=[('Tramo', 'Tramo'), ('Juego', 'Juego')], default='Juego', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='available_date_from',
            field=models.DateTimeField(verbose_name='Disponiible desde el'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='available_date_to',
            field=models.DateTimeField(verbose_name='Disponible hasta el'),
        ),
    ]
