# Generated by Django 5.1.5 on 2025-07-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0071_gameevent_description_gameevent_free_join_and_more'),
        ('rewards_api', '0013_alter_reward_options_alter_rewardbundle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='reward_bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards_api.rewardbundle'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='available_date_from',
            field=models.DateTimeField(verbose_name='Disponible desde el'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='requirements',
            field=models.TextField(null=True, verbose_name='Requisitos'),
        ),
    ]
