# Generated by Django 5.1.5 on 2025-07-30 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0072_gameevent_reward_bundle_and_more'),
        ('rewards_api', '0013_alter_reward_options_alter_rewardbundle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='text_reward',
            field=models.TextField(blank=True, null=True, verbose_name='Recompensa especial'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='reward_bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards_api.rewardbundle', verbose_name='Preset de recompensa'),
        ),
    ]
