# Generated by Django 5.1.5 on 2025-07-31 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0073_gameevent_text_reward_alter_gameevent_reward_bundle'),
        ('rewards_api', '0013_alter_reward_options_alter_rewardbundle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameevent',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='for_noobs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='for_pros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='reward_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards_api.rewardbundle', verbose_name='Preset de recompensa'),
        ),
    ]
