# Generated by Django 5.1.5 on 2025-07-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0074_alter_gameevent_options_newsletter_for_noobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='is_wip',
            field=models.BooleanField(default=False, verbose_name='Esta en desarrollo'),
        ),
    ]
