# Generated by Django 5.1.5 on 2025-07-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0075_wildcard_is_wip'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='for_staff',
            field=models.BooleanField(default=False),
        ),
    ]
