# Generated by Django 5.1.5 on 2025-08-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0076_newsletter_for_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='main_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.mastersprofile'),
        ),
    ]
