# Generated by Django 5.1.5 on 2025-08-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0077_mastersprofile_main_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimposterlog',
            name='registered_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='imposter',
            name='coin_reward',
            field=models.IntegerField(default=1, help_text='Maxima cantidad de monedas a obtener (SIN CONTAR A LOS PRIMEROS 10)'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='web_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/web/'),
        ),
    ]
