# Generated by Django 5.1.5 on 2025-08-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0078_profileimposterlog_registered_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterssegmentsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Fecha de Creacion', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterssegmentsettings',
            name='finished_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Finalizacion de tramo'),
        ),
    ]
