# Generated by Django 5.1.5 on 2025-08-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0079_masterssegmentsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterssegmentsettings',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalizacion de tramo'),
        ),
    ]
