# Generated by Django 5.1.5 on 2025-08-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0080_alter_masterssegmentsettings_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='showdown_token',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
