# Generated by Django 5.1.5 on 2025-08-19 01:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_showdowntoken'),
        ('event_api', '0081_mastersprofile_showdown_token'),
        ('trainer_data', '0022_alter_trainerpokemon_enc_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersprofile',
            name='already_won_lysson',
            field=models.BooleanField(default=False, verbose_name='Le ganó a Lysson'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='coached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='event_api.mastersprofile', verbose_name='Ahijado'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='death_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conteo de muertes totales'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='in_pokemon_league',
            field=models.BooleanField(default=False, verbose_name='Dentro de la liga'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='Es pro?'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='is_tester',
            field=models.BooleanField(default=False, verbose_name='Es Tester?'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='main_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.mastersprofile', verbose_name='Coach principal'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='profile_type',
            field=models.SmallIntegerField(choices=[(0, 'Trainer'), (1, 'Coach'), (2, 'Admin')], default=0, verbose_name='Tipo de Perfil'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='rom_name',
            field=models.CharField(default='Pokémon X', max_length=50, verbose_name='Nombre de Rom'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='showdown_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.showdowntoken', verbose_name='Token para showdown'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='starter_dex_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pokémon "El Elegido"'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='streamer_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nombre de Streamer'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='tournament_league',
            field=models.CharField(choices=[('-', '------'), ('A', 'Liga A'), ('B', 'Liga B'), ('C', 'Liga C'), ('D', 'Liga D'), ('E', 'Liga E')], default='-', max_length=1, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='trainer_data.trainer', verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='web_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/web/', verbose_name='Foto Perfil'),
        ),
    ]
