# Generated by Django 5.1.5 on 2025-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0082_alter_mastersprofile_already_won_lysson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='has_animated_overlay',
            field=models.BooleanField(default=False, verbose_name='Overlay Animado'),
        ),
    ]
