# Generated by Django 5.1.5 on 2025-08-21 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0083_mastersprofile_has_animated_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='death_count_display',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conteo de muertes totales para overlay'),
        ),
    ]
