# Generated by Django 5.1.5 on 2025-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0084_mastersprofile_death_count_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='StealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('pokemon', models.CharField(max_length=50)),
            ],
        ),
    ]
