# Generated by Django 5.1.5 on 2025-08-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0085_steallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
