# Generated by Django 5.1.5 on 2025-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0086_mastersprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.IntegerField(db_index=True)),
                ('root_evolution', models.IntegerField(db_index=True)),
            ],
        ),
    ]
