# Generated by Django 5.1.5 on 2025-08-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0088_profilenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='for_tester',
            field=models.BooleanField(default=False),
        ),
    ]
