# Generated by Django 5.1.5 on 2025-08-25 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0090_alter_masterssegmentsettings_attacks_received_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterssegmentsettings',
            name='attacks_received_left',
            field=models.DecimalField(decimal_places=1, default=4, help_text='Ataques que puede recibir en el tramo', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='masterssegmentsettings',
            name='karma',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Capacidad de usar comodines de ataque fuerte', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Karma'),
        ),
    ]
