# Generated by Django 5.1.5 on 2025-08-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0091_alter_masterssegmentsettings_attacks_received_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('money_substracted', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='event_api.mastersprofile')),
            ],
            options={
                'verbose_name': 'Sancion',
                'verbose_name_plural': 'Sanciones',
            },
        ),
    ]
