# Generated by Django 5.1.5 on 2025-08-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0092_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='send_notification',
            field=models.BooleanField(default=False, verbose_name='Enviar Notificacion'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='for_noobs',
            field=models.BooleanField(default=False, verbose_name='Incluye Noobs'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='for_pros',
            field=models.BooleanField(default=False, verbose_name='Incluye Pros'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='for_staff',
            field=models.BooleanField(default=False, verbose_name='Solo Para Staff'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='for_tester',
            field=models.BooleanField(default=False, verbose_name='Solo Para Testers'),
        ),
    ]
