# Generated by Django 5.1.5 on 2025-08-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0093_newsletter_send_notification_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileimposterlog',
            unique_together={('profile', 'imposter')},
        ),
    ]
