# Generated by Django 5.1.5 on 2025-08-26 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0094_alter_profileimposterlog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='money_substracted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
