# Generated by Django 5.1.5 on 2025-08-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0095_alter_sanction_money_substracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='targets',
            field=models.ManyToManyField(blank=True, null=True, to='event_api.mastersprofile'),
        ),
    ]
