# Generated by Django 5.1.5 on 2025-08-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0096_newsletter_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildcardUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcard_update_logs', to='event_api.mastersprofile')),
            ],
        ),
    ]
