# Generated by Django 5.1.5 on 2025-08-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0097_wildcardupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Configuracion de tramo',
                'verbose_name_plural': 'Configuraciones de tramo',
            },
        ),
    ]
