# Generated by Django 5.1.5 on 2025-08-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0098_segmentconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildcard',
            name='segment_available',
            field=models.IntegerField(default=0),
        ),
    ]
