# Generated by Django 5.1.5 on 2025-08-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0099_wildcard_segment_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentconfiguration',
            name='is_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
