# Generated by Django 5.1.5 on 2025-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0100_segmentconfiguration_is_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='targets',
            field=models.ManyToManyField(blank=True, to='event_api.mastersprofile'),
        ),
    ]
