# Generated by Django 5.1.5 on 2025-08-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0101_alter_newsletter_targets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wildcardupdatelog',
            options={'verbose_name': 'Registro de inventario de comodin', 'verbose_name_plural': 'Registros de inventario de comodines'},
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='segment',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profileimposterlog',
            name='imposter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.imposter', verbose_name='Impostor'),
        ),
        migrations.AlterField(
            model_name='profileimposterlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imposters', to='event_api.mastersprofile', verbose_name='Jugador'),
        ),
        migrations.AlterField(
            model_name='profileimposterlog',
            name='registered_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Monedas Registradas'),
        ),
    ]
