# Generated by Django 5.1.5 on 2025-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0102_alter_wildcardupdatelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_2_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_3_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_4_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_5_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_6_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_7_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
        migrations.AddField(
            model_name='mastersprofile',
            name='gym_8_save',
            field=models.FileField(blank=True, null=True, upload_to='profile/saves/'),
        ),
    ]
