# Generated by Django 5.1.5 on 2025-08-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0103_mastersprofile_gym_2_save_mastersprofile_gym_3_save_and_more'),
        ('rewards_api', '0029_alter_roulettepricewildcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steallog',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rewards_api.rewardbundle'),
        ),
        migrations.CreateModel(
            name='AlreadyCapturedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.IntegerField()),
                ('pid', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='event_api.mastersprofile')),
            ],
        ),
    ]
