# Generated by Django 5.1.5 on 2025-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0104_steallog_bundle_alreadycapturedlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathlog',
            name='segment',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
