# Generated by Django 5.1.5 on 2025-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0105_deathlog_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='imposter',
            name='segment',
            field=models.IntegerField(default=1, verbose_name='Tramo'),
        ),
    ]
