# Generated by Django 5.1.5 on 2025-08-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0106_imposter_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='testers_only',
            field=models.BooleanField(default=False),
        ),
    ]
