# Generated by Django 5.1.5 on 2025-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0107_gameevent_testers_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='event_joined_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
