# Generated by Django 5.1.5 on 2025-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0108_mastersprofile_event_joined_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='wipe_clause_available',
            field=models.BooleanField(default=False, verbose_name='Clausula de Wipeo Disponible'),
        ),
    ]
