# Generated by Django 5.1.5 on 2025-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0109_mastersprofile_wipe_clause_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersprofile',
            name='wipe_clause_available',
            field=models.BooleanField(default=True, verbose_name='Clausula de Wipeo Disponible'),
        ),
    ]
