# Generated by Django 5.1.5 on 2025-08-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0110_alter_mastersprofile_wipe_clause_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='for_noobs',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='for_pros',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='run_on_save',
            field=models.BooleanField(default=False, verbose_name='Ejecutar al guardar'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='target_method',
            field=models.SmallIntegerField(choices=[(0, 'All'), (1, 'Pros'), (2, 'Noobs'), (3, 'Sleccionado')], default=0),
        ),
    ]
