# Generated by Django 5.1.5 on 2025-08-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0111_remove_newsletter_for_noobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='for_staff',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='for_tester',
        ),
    ]
