# Generated by Django 5.1.5 on 2025-08-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0112_remove_newsletter_for_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='target_method',
            field=models.SmallIntegerField(choices=[(0, 'Todos'), (1, 'Pros'), (2, 'Noobs'), (3, 'Sleccionado')], default=0, verbose_name='Objetivos de envío'),
        ),
    ]
