# Generated by Django 5.1.5 on 2025-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0113_alter_newsletter_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='targets',
            field=models.ManyToManyField(blank=True, to='event_api.mastersprofile', verbose_name='Objetivos Seleccionados'),
        ),
    ]
