# Generated by Django 5.1.5 on 2025-08-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0114_alter_newsletter_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='target_method',
            field=models.SmallIntegerField(choices=[(0, 'Todos'), (1, 'Pros'), (2, 'Noobs'), (3, 'Seleccionado')], default=0, verbose_name='Objetivos de envío'),
        ),
    ]
