# Generated by Django 5.1.5 on 2025-09-01 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0115_alter_newsletter_target_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterssegmentsettings',
            name='death_count_display',
            field=models.IntegerField(default=0, help_text='Muertes en el tramo del overlay', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
