# Generated by Django 5.1.5 on 2025-09-02 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0116_masterssegmentsettings_death_count_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterssegmentsettings',
            name='attacks_received_left',
        ),
        migrations.AddField(
            model_name='masterssegmentsettings',
            name='attacks_received',
            field=models.IntegerField(default=0, help_text='Ataques que ha recibido en el tramo', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ataques Recibidos'),
        ),
        migrations.AddField(
            model_name='wildcard',
            name='noob_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterssegmentsettings',
            name='steal_karma',
            field=models.IntegerField(default=0, help_text='Al juntar 3, se desbloquea "Robo justo"', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Karma de Robo Justo'),
        ),
    ]
