# Generated by Django 5.1.5 on 2025-09-03 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0117_remove_masterssegmentsettings_attacks_received_left_and_more'),
        ('pokemon_api', '0010_alter_pokemonnature_stat_down_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractPokemonDataSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('run_on_save', models.BooleanField(default=False, verbose_name='Ejecutar al guardar')),
                ('last_ran_at', models.DateTimeField(verbose_name='Ultima ejecucion')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='event_api.mastersprofile', verbose_name='Objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionPokemonProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enc_data', models.FileField(blank=True, null=True, upload_to='extraction/pokemon/', verbose_name='EK6 data')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_targeted', to='pokemon_api.pokemon', verbose_name='Pokemon Objetivo')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='event_api.extractpokemondatasequence')),
            ],
        ),
    ]
