# Generated by Django 5.1.5 on 2025-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0118_extractpokemondatasequence_extractionpokemonprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractpokemondatasequence',
            name='target',
        ),
        migrations.DeleteModel(
            name='ExtractionPokemonProcess',
        ),
        migrations.DeleteModel(
            name='ExtractPokemonDataSequence',
        ),
    ]
