# Generated by Django 5.1.5 on 2025-09-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0119_remove_extractpokemondatasequence_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterssegmentsettings',
            name='justice_steal_bought',
            field=models.BooleanField(default=False, verbose_name='Robo justo comprado'),
        ),
        migrations.AlterField(
            model_name='mastersprofile',
            name='event_joined_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Evento iniciado'),
        ),
    ]
