# Generated by Django 5.1.5 on 2025-09-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0120_masterssegmentsettings_justice_steal_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='only_for_noobs',
            field=models.BooleanField(default=False),
        ),
    ]
