# Generated by Django 5.1.5 on 2026-02-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0121_gameevent_only_for_noobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alreadycapturedlog',
            name='dex_number',
            field=models.IntegerField(null=True),
        ),
    ]
