# Generated by Django 5.1.5 on 2026-02-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0122_alter_alreadycapturedlog_dex_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersprofile',
            name='rom_name',
            field=models.CharField(default='Pokémon ORAS', max_length=50, verbose_name='Nombre de Rom'),
        ),
    ]
