# Generated by Django 5.1.5 on 2026-02-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0123_alter_mastersprofile_rom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersprofile',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Fighting'), (2, 'Flying'), (3, 'Poison'), (4, 'Ground'), (5, 'Rock'), (6, 'Bug'), (7, 'Ghost'), (8, 'Steel'), (9, 'Fire'), (10, 'Water'), (11, 'Grass'), (12, 'Electric'), (13, 'Psychic'), (14, 'Ice'), (15, 'Dragon'), (16, 'Dark'), (17, 'Fairy')], default=0, verbose_name='Tipo en Overlay'),
        ),
    ]
