# Generated by Django 5.1.5 on 2025-01-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('localization', models.CharField(db_index=True, default='en', max_length=2, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('localization', models.CharField(db_index=True, default='en', max_length=2, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Pokemon Abilities',
            },
        ),
        migrations.CreateModel(
            name='PokemonNature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('localization', models.CharField(db_index=True, default='en', max_length=2, null=True)),
                ('stat_up', models.CharField(choices=[('ATTACK', 'ATTACK'), ('DEFENSE', 'DEFENSE'), ('SPECIAL_ATTACK', 'SPECIAL ATTACK'), ('SPECIAL_DEFENSE', 'SPECIAL DEFENSE'), ('SPEED', 'SPEED')], max_length=50)),
                ('stat_down', models.CharField(choices=[('ATTACK', 'ATTACK'), ('DEFENSE', 'DEFENSE'), ('SPECIAL_ATTACK', 'SPECIAL ATTACK'), ('SPECIAL_DEFENSE', 'SPECIAL DEFENSE'), ('SPEED', 'SPEED')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('localization', models.CharField(db_index=True, default='en', max_length=2, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoveCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('localization', models.CharField(db_index=True, default='en', max_length=2, null=True)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Move Categories',
                'constraints': [models.UniqueConstraint(fields=('localization', 'index'), name='localizated_index')],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('index', models.IntegerField()),
                ('localization', models.CharField(db_index=True, default='en', max_length=2, null=True)),
                ('name', models.CharField(max_length=50)),
                ('max_pp', models.IntegerField()),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('flavor_text', models.TextField()),
                ('contact_flag', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pokemon_api.movecategory')),
                ('move_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon_api.type')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dex_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('form', models.CharField(default='0', max_length=20)),
                ('sprite', models.ImageField(upload_to='media/pokemon_sprites/')),
                ('types', models.ManyToManyField(to='pokemon_api.type')),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
                'constraints': [models.UniqueConstraint(fields=('dex_number', 'form'), name='form_dex_number')],
            },
        ),
    ]
