# Generated by Django 5.1.5 on 2025-01-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCoverage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=1, max_digits=2)),
                ('type_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coveages_from', to='pokemon_api.type')),
                ('type_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages_to', to='pokemon_api.type')),
            ],
        ),
    ]
