# Generated by Django 5.1.5 on 2025-01-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0002_typecoverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextLocalization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(max_length=2)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='movecategory',
            name='localizated_index',
        ),
        migrations.AlterField(
            model_name='typecoverage',
            name='type_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages_from', to='pokemon_api.type'),
        ),
        migrations.AddField(
            model_name='move',
            name='flavor_text_localizations',
            field=models.ManyToManyField(blank=True, related_name='move_flavor_texts', to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='move',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, related_name='move_names', to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='movecategory',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='pokemonability',
            name='flavor_text_localizations',
            field=models.ManyToManyField(blank=True, related_name='ability_flavor_texts', to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='pokemonability',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, related_name='ability_names', to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='pokemonnature',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='type',
            name='flavor_text_localizations',
            field=models.ManyToManyField(blank=True, related_name='type_flavor_texts', to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, related_name='type_names', to='pokemon_api.contextlocalization'),
        ),
    ]
