# Generated by Django 5.1.5 on 2025-01-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0003_contextlocalization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flavor_text_localizations',
            field=models.ManyToManyField(blank=True, related_name='item_flavor_texts', to='pokemon_api.contextlocalization'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, related_name='item_names', to='pokemon_api.contextlocalization'),
        ),
        migrations.AlterField(
            model_name='contextlocalization',
            name='language',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
