# Generated by Django 5.1.5 on 2025-06-15 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0004_item_flavor_text_localizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name_localizations',
            field=models.ManyToManyField(blank=True, related_name='item_names2', to='pokemon_api.contextlocalization'),
        ),
        migrations.CreateModel(
            name='ItemNameLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=2, null=True)),
                ('content', models.TextField(null=True)),
                ('item', models.ForeignKey(db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_names', to='pokemon_api.item')),
            ],
        ),
    ]
