# Generated by Django 5.1.5 on 2025-06-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0005_alter_item_name_localizations_itemnamelocalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name_localizations',
        ),
        migrations.AlterField(
            model_name='itemnamelocalization',
            name='item',
            field=models.ForeignKey(db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_localizations', to='pokemon_api.item'),
        ),
    ]
