# Generated by Django 5.1.5 on 2025-06-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0006_remove_item_name_localizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='api_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
