# Generated by Django 5.1.5 on 2025-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0007_item_api_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_bag',
            field=models.CharField(blank=True, choices=[('berries', 'berries bag'), ('meds', 'meds bag'), ('tms', 'tms bag'), ('keys', 'keys bag'), ('items', 'items bag')], max_length=100, null=True),
        ),
    ]
