# Generated by Django 5.1.5 on 2025-08-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0008_item_item_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom_sprite',
            field=models.ImageField(blank=True, null=True, upload_to='sprites/'),
        ),
    ]
