# Generated by Django 5.1.5 on 2025-08-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0009_item_custom_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonnature',
            name='stat_down',
            field=models.CharField(blank=True, choices=[('ATTACK', 'ATTACK'), ('DEFENSE', 'DEFENSE'), ('SPECIAL_ATTACK', 'SPECIAL ATTACK'), ('SPECIAL_DEFENSE', 'SPECIAL DEFENSE'), ('SPEED', 'SPEED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonnature',
            name='stat_up',
            field=models.CharField(blank=True, choices=[('ATTACK', 'ATTACK'), ('DEFENSE', 'DEFENSE'), ('SPECIAL_ATTACK', 'SPECIAL ATTACK'), ('SPECIAL_DEFENSE', 'SPECIAL DEFENSE'), ('SPEED', 'SPEED')], max_length=50, null=True),
        ),
    ]
