# Generated by Django 5.1.5 on 2026-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0010_alter_pokemonnature_stat_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlocalization',
            name='extra',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pokemonability',
            name='flavor_text',
            field=models.TextField(default=''),
        ),
    ]
