# Generated by Django 5.1.5 on 2025-03-24 05:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_api', '0020_savefile_accessible'),
        ('pokemon_api', '0004_item_flavor_text_localizations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.SmallIntegerField(choices=[(0, 'Item'), (1, 'Wildcard'), (2, 'Money'), (3, 'Pokemon')], default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_data', models.FileField(upload_to='pokemon_rewards')),
                ('pokemon_pid', models.PositiveIntegerField(db_index=True, unique=True)),
                ('reward', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_reward', to='rewards_api.reward')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reward', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_reward', to='rewards_api.reward')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_api.item')),
                ('reward', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_reward', to='rewards_api.reward')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards_api.rewardbundle'),
        ),
        migrations.CreateModel(
            name='WildcardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reward', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wildcard_reward', to='rewards_api.reward')),
                ('wildcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.wildcard')),
            ],
        ),
    ]
