# Generated by Django 5.1.5 on 2025-03-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardbundle',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rewardbundle',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
