# Generated by Django 5.1.5 on 2025-03-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0002_rewardbundle_description_rewardbundle_name'),
        ('trainer_data', '0010_remove_trainerpokemon_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonreward',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer_data.trainerpokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonreward',
            name='reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_reward', to='rewards_api.reward'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='rewards_api.rewardbundle'),
        ),
        migrations.AlterField(
            model_name='rewardbundle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
