# Generated by Django 5.1.5 on 2025-03-24 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0025_remove_streamer_rewards'),
        ('rewards_api', '0003_pokemonreward_pokemon_alter_pokemonreward_reward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerRewardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchanges', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards_api.rewardbundle')),
                ('streamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='event_api.streamer')),
            ],
            options={
                'unique_together': {('reward', 'streamer')},
            },
        ),
    ]
