# Generated by Django 5.1.5 on 2025-05-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0005_itemreward_bag_alter_streamerrewardinventory_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonreward',
            name='pokemon_pid',
            field=models.PositiveIntegerField(blank=True, db_index=True, unique=True),
        ),
    ]
