# Generated by Django 5.1.5 on 2025-07-24 05:08

import django.db.models.deletion
from django.db import migrations, models


def declare_profile(apps, schema_editor):
    StreamerRewardInventory = apps.get_model("rewards_api", "StreamerRewardInventory")
    for item in StreamerRewardInventory.objects.all():
        item.profile = item.streamer.user.masters_profile
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event_api', '0053_remove_cointransaction_trainer_and_more'),
        ('rewards_api', '0006_alter_pokemonreward_pokemon_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamerrewardinventory',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='reward_inventory', to='event_api.mastersprofile'),
        ),
        migrations.RunPython(
            declare_profile
        )
    ]
