# Generated by Django 5.1.5 on 2025-07-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0057_alter_deathlog_pid_alter_deathlog_species_name_and_more'),
        ('rewards_api', '0007_streamerrewardinventory_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streamerrewardinventory',
            unique_together={('reward', 'profile')},
        ),
        migrations.RemoveField(
            model_name='streamerrewardinventory',
            name='streamer',
        ),
    ]
