# Generated by Django 5.1.5 on 2025-07-26 11:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0057_alter_deathlog_pid_alter_deathlog_species_name_and_more'),
        ('pokemon_api', '0008_item_item_bag'),
        ('rewards_api', '0008_alter_streamerrewardinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyreward',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='wildcardreward',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='wildcardreward',
            name='wildcard',
        ),
        migrations.AddField(
            model_name='reward',
            name='bag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_api.item'),
        ),
        migrations.AddField(
            model_name='reward',
            name='pokemon_data',
            field=models.FileField(blank=True, null=True, upload_to='pokemon_rewards'),
        ),
        migrations.AddField(
            model_name='reward',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='reward',
            name='wildcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.wildcard'),
        ),
        migrations.DeleteModel(
            name='ItemReward',
        ),
        migrations.DeleteModel(
            name='MoneyReward',
        ),
        migrations.DeleteModel(
            name='WildcardReward',
        ),
    ]
