# Generated by Django 5.1.5 on 2025-07-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0009_remove_moneyreward_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='bag',
        ),
    ]
