# Generated by Django 5.1.5 on 2025-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0010_remove_reward_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='pokemon_pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PokemonReward',
        ),
    ]
