# Generated by Django 5.1.5 on 2025-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0011_reward_pokemon_pid_delete_pokemonreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='pokemon_pid',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
