# Generated by Django 5.1.5 on 2025-07-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0012_alter_reward_pokemon_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Elemento del Inventario', 'verbose_name_plural': 'Elementos del Inventario'},
        ),
        migrations.AlterModelOptions(
            name='rewardbundle',
            options={'verbose_name': 'Preset De Inventario', 'verbose_name_plural': 'Presets de Inventario'},
        ),
    ]
