# Generated by Django 5.1.5 on 2025-08-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0013_alter_reward_options_alter_rewardbundle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamerrewardinventory',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
    ]
