# Generated by Django 5.1.5 on 2025-08-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0014_streamerrewardinventory_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamerrewardinventory',
            name='user_created',
        ),
        migrations.AddField(
            model_name='rewardbundle',
            name='user_created',
            field=models.BooleanField(default=False),
        ),
    ]
