# Generated by Django 5.1.5 on 2025-08-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0015_remove_streamerrewardinventory_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardbundle',
            name='sender',
            field=models.CharField(default='Evento', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rewardbundle',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Premio'), (1, 'Ruleta'), (2, 'Comodin')], default=0),
        ),
    ]
