# Generated by Django 5.1.5 on 2025-08-20 21:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0083_mastersprofile_has_animated_overlay'),
        ('rewards_api', '0016_rewardbundle_sender_rewardbundle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='ruletas/')),
                ('recreate_at_save', models.BooleanField(default=False, verbose_name='Recrear al guardar')),
            ],
            options={
                'verbose_name': 'Ruleta',
                'verbose_name_plural': 'Ruletas',
            },
        ),
        migrations.CreateModel(
            name='RoulettePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rewards_api.roulette')),
                ('wildcard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_api.wildcard', verbose_name='Comodin')),
            ],
        ),
    ]
