# Generated by Django 5.1.5 on 2025-08-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0017_roulette_rouletteprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulette',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
