# Generated by Django 5.1.5 on 2025-08-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0083_mastersprofile_has_animated_overlay'),
        ('rewards_api', '0018_alter_roulette_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rouletteprice',
            name='wildcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event_api.wildcard', verbose_name='Comodin'),
        ),
    ]
