# Generated by Django 5.1.5 on 2025-08-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0019_alter_rouletteprice_wildcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rouletteprice',
            options={'verbose_name': 'Premio de Ruleta', 'verbose_name_plural': 'Premios de Ruleta'},
        ),
        migrations.AddField(
            model_name='roulette',
            name='banner_image',
            field=models.ImageField(help_text='Imagen grande del Banner', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='roulette',
            name='banner_logo',
            field=models.ImageField(help_text='Logo chico del banner', null=True, upload_to='banners/'),
        ),
    ]
