# Generated by Django 5.1.5 on 2025-08-21 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0084_mastersprofile_death_count_display'),
        ('rewards_api', '0020_alter_rouletteprice_options_roulette_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='wildcard',
            field=models.ForeignKey(blank=True, help_text='Comodin usado para validar tiradas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_api.wildcard', verbose_name='Comodin Asignada'),
        ),
    ]
