# Generated by Django 5.1.5 on 2025-08-22 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0021_roulette_wildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden vertical'),
        ),
        migrations.AddField(
            model_name='roulette',
            name='segment',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Tramo Para Aparecer'),
        ),
    ]
