# Generated by Django 5.1.5 on 2025-08-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0022_roulette_order_roulette_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardbundle',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
