# Generated by Django 5.1.5 on 2025-08-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0085_steallog'),
        ('rewards_api', '0023_alter_rewardbundle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteRollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje de Display')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Tirada')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_hiistory', to='event_api.mastersprofile', verbose_name='perfil')),
                ('roulette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='rewards_api.roulette', verbose_name='Ruleta')),
            ],
        ),
    ]
