# Generated by Django 5.1.5 on 2025-08-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0024_rouletterollhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rouletterollhistory',
            options={'verbose_name': 'Hitoria de Ruleta', 'verbose_name_plural': 'Historial de tiradas de Ruleta'},
        ),
    ]
