# Generated by Django 5.1.5 on 2025-08-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0025_alter_rouletterollhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='active_banner_logo',
            field=models.ImageField(help_text='Logo chico del banner activo', null=True, upload_to='banners/'),
        ),
    ]
