# Generated by Django 5.1.5 on 2025-08-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0026_roulette_active_banner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='jackpot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
