# Generated by Django 5.1.5 on 2025-08-24 06:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0086_mastersprofile_description'),
        ('rewards_api', '0027_roulette_jackpot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rouletteprice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rouletteprice',
            name='wildcard',
        ),
        migrations.AddField(
            model_name='rouletteprice',
            name='is_jackpot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rouletteprice',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RoulettePriceWildcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcards', to='rewards_api.rouletteprice')),
                ('wildcard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event_api.wildcard', verbose_name='Comodin')),
            ],
            options={
                'verbose_name': 'Premio de Ruleta',
                'verbose_name_plural': 'Premios de Ruleta',
            },
        ),
    ]
