# Generated by Django 5.1.5 on 2025-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_api', '0028_remove_rouletteprice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roulettepricewildcard',
            options={'verbose_name': 'Comodin de Premio', 'verbose_name_plural': 'Comodines de Premios'},
        ),
        migrations.RemoveField(
            model_name='roulette',
            name='jackpot_name',
        ),
        migrations.AddField(
            model_name='rouletteprice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roulette/images/'),
        ),
    ]
